behaviors:
  BrainBlob:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2

      lambd: 0.9
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      conditioning_type: none
      vis_encode_type: resnet
      normalize: true
      hidden_units: 256
      num_layers: 2
      use recurrent: true
      memory:
        memory_size: 128
        sequence_length: 64



    # Trainer configurations common to all trainers
    max_steps: 1.0e6
    time_horizon: 128

    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null



    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

  BrainBlyb:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 512
      buffer_size: 2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2

      lambd: 0.9
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      conditioning_type: none
      vis_encode_type: resnet
      normalize: true
      hidden_units: 256
      num_layers: 2
      use recurrent: true
      memory:
        memory_size: 128
        sequence_length: 64



    # Trainer configurations common to all trainers
    max_steps: 1.0e6
    time_horizon: 128

    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null



    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

  BrainBlub:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 512
      buffer_size: 2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2

      lambd: 0.9
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      conditioning_type: none
      vis_encode_type: resnet
      normalize: true
      hidden_units: 256
      num_layers: 2
      use recurrent: true
      memory:
        memory_size: 128
        sequence_length: 64



    # Trainer configurations common to all trainers
    max_steps: 1.0e6
    time_horizon: 128

    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    init_path: null



    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99
